name: CMake

on:
  pull_request:
  push:

env:
  config: Release
  build_dir: build

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      working-directory: ${{ github.workspace }}/dlib/test
      run: cmake . -B ${{ env.build_dir }}

    - name: Build just tests
      working-directory: ${{ github.workspace }}/dlib/test
      run: cmake --build ${{ env.build_dir }} --config ${{ env.config }} --target dtest --parallel 8

    - name: Test
      working-directory: ${{ github.workspace }}/dlib/test/${{ env.build_dir }}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./${{ env.config }}/dtest.exe --runall -q
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ./dtest --runall --no_test_timer -q
        else
          ./dtest --runall -q
        fi;

    - name: Build examples, etc
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      working-directory: ${{ github.workspace }}/dlib/test
      run: cmake --build ${{ env.build_dir }} --config ${{ env.config }} --parallel 8
